name: khqr_sdk
description: 'Standardization of QR Code (EMV) that will promote wider use of mobile retail payments in Cambodia.'
maintainer: Mrr Hak
repository: https://github.com/mrrhak/khqr_sdk
issue_tracker: https://github.com/mrrhak/khqr_sdk/issues
homepage: https://mrrhak.com
version: 2.0.1
funding:
  - https://ko-fi.com/mrrhak
screenshots:
  - description: 'Bakong KHQR SDK'
    path: assets/khqr_sdk.png

topics:
  - khqr
  - khqr-sdk
  - khqr-code
  - bakong-khqr
  - bakong

environment:
  sdk: ^3.9.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.18.1 <=0.20.2"
  crypto: ^3.0.6
  http: ^1.5.0
  pretty_qr_code: ^3.5.0
  flutter_svg: ^2.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/fonts/nunito_sans/
    - assets/images/
    - assets/svg/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/nunito_sans/NunitoSans_7pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito_sans/NunitoSans_7pt-Bold.ttf
          weight: 700